# Generated by Django 3.0.8 on 2020-07-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='status',
        ),
    ]
