# Generated by Django 3.0.8 on 2020-07-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0002_remove_usuario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=240),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nome',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
