# Generated by Django 3.0.8 on 2020-07-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCaixaRealizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situação', models.CharField(max_length=140)),
                ('data', models.CharField(max_length=10000)),
                ('cliente_fornecedor', models.CharField(max_length=10000)),
                ('tipo_de_documento', models.CharField(max_length=10000)),
                ('valor', models.CharField(max_length=10000)),
                ('saldo', models.CharField(max_length=10000)),
                ('categoria', models.CharField(max_length=10000)),
                ('nota_fiscal', models.CharField(max_length=1000)),
                ('parcela', models.CharField(max_length=10000)),
                ('nosso_numero', models.CharField(max_length=10000)),
                ('origem', models.CharField(max_length=10000)),
                ('pedido', models.CharField(max_length=10000)),
                ('vendedor', models.CharField(max_length=10000)),
                ('projeto', models.CharField(max_length=10000)),
                ('cliente_fornecedor_razao_social', models.CharField(max_length=10000)),
                ('cliente_fornecedor_cnpj', models.CharField(max_length=10000)),
                ('observacao', models.CharField(max_length=10000)),
                ('incluido_em', models.CharField(max_length=10000)),
                ('conta', models.CharField(max_length=10000)),
                ('chaveclassificacao', models.CharField(max_length=10000)),
                ('tipo', models.CharField(max_length=10000)),
                ('classificacao_caixa', models.CharField(max_length=10000)),
                ('dia_baixa', models.CharField(max_length=10000)),
                ('mes_baixa', models.CharField(max_length=10000)),
                ('ano_baixa', models.CharField(max_length=10000)),
                ('classificacao_resultado', models.CharField(max_length=10000)),
            ],
        ),
    ]
