# Generated by Django 3.0.8 on 2020-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVendasRealizadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_faturamento_2', models.CharField(default=0, max_length=240)),
                ('cliente_faturamento_2', models.CharField(default=0, max_length=1000)),
                ('pedido_vendas_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('produto_2', models.CharField(default=0, max_length=1000)),
                ('ano_faturamento_2', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('dia_faturamento_2', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('mes_faturamento_2', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('quantidade_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_mercadoria_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('desconto_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('valor_icms_st_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('frete_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('seguro_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('outras_desp_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('valor_ipi_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('notal_nf_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('valor_icms_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('valor_pis_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('valor_cofins_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('classificacao_resultado_faturamento_2', models.CharField(default=0, max_length=240)),
                ('data_faturamento_2', models.DateField(default=0)),
                ('valor_cmv_unit_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('valor_cmv_total_2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='ano_baixa',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='chaveclassificacao',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='cliente_fornecedor',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='cliente_fornecedor_cnpj',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='cliente_fornecedor_razao_social',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='dia_baixa',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='incluido_em',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='mes_baixa',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='nosso_numero',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='situação',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='tipo_de_documento',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='ano_pagamento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='cliente',
            field=models.CharField(default=0, max_length=240),
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='dia_pagamento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='mes_pagamento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='situacao',
            field=models.CharField(blank=True, default=0, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='classificacao_caixa',
            field=models.CharField(default=0, max_length=240),
        ),
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='classificacao_resultado',
            field=models.CharField(default=0, max_length=240),
        ),
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='data',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
