# Generated by Django 3.0.8 on 2020-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamama', '0002_auto_20200714_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='ano_baixa',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='chaveclassificacao',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='cliente_fornecedor',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='cliente_fornecedor_cnpj',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='cliente_fornecedor_razao_social',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='dia_baixa',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='incluido_em',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='mes_baixa',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='nosso_numero',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='situação',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='tipo_de_documento',
        ),
        migrations.RemoveField(
            model_name='basecaixarealizado',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='ano_pagamento',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='cliente',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='dia_pagamento',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='mes_pagamento',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecaixarealizado',
            name='situacao',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='classificacao_caixa',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='classificacao_resultado',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
