# Generated by Django 3.0.8 on 2020-07-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamama', '0003_auto_20200715_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecaixarealizado',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
