# Generated by Django 3.0.8 on 2020-07-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamama', '0004_auto_20200717_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVendasRealizadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_faturamento_2', models.CharField(max_length=240)),
                ('cliente_faturamento_2', models.CharField(max_length=240)),
                ('pedido_vendas_2', models.CharField(max_length=240)),
                ('produto_2', models.CharField(max_length=1000)),
                ('ano_faturamento_2', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dia_faturamento_2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('mes_faturamento_2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('quantidade_2', models.DecimalField(decimal_places=0, max_digits=100)),
                ('total_mercadoria_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('desconto_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('valor_icms_st_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('frete_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('seguro_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('outras_desp_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('valor_ipi_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('notal_nf_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('valor_icms_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('valor_pis_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('valor_cofins_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('classificacao_resultado_faturamento_2', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('data_faturamento_2', models.DateField()),
            ],
        ),
    ]
