# Generated by Django 3.0.8 on 2020-07-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamama', '0005_basevendasrealizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='classificacao_resultado_faturamento_2',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='pedido_vendas_2',
            field=models.DecimalField(decimal_places=0, max_digits=100000),
        ),
    ]
