# Generated by Django 3.0.8 on 2020-07-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pachamama', '0007_auto_20200724_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basevendasrealizadas',
            name='valor_cmv_total_2',
        ),
        migrations.RemoveField(
            model_name='basevendasrealizadas',
            name='valor_cmv_unit_2',
        ),
    ]
