# Generated by Django 3.0.8 on 2020-07-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamama', '0008_auto_20200728_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevendasrealizadas',
            name='valor_cmv_total_2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basevendasrealizadas',
            name='valor_cmv_unit_2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000),
            preserve_default=False,
        ),
    ]
