# Generated by Django 3.0.8 on 2020-07-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamama', '0009_auto_20200728_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='desconto_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='frete_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='notal_nf_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='outras_desp_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='pedido_vendas_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='quantidade_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='seguro_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='total_mercadoria_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='valor_cmv_total_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='valor_cmv_unit_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='valor_cofins_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='valor_icms_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='valor_icms_st_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='valor_ipi_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='basevendasrealizadas',
            name='valor_pis_2',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
